name: Discord Based Activity README Updater

on:
  schedule:
    - cron: "* * /1 * * *" # Customizable by Choices.
  workflow_dispatch:

jobs:
  ActivityUpdater:
    name: Discord Activity Watcher
    runs-on: ubuntu-20.04
    env:
      DISCORD_ID_SECRET: ${{ secrets.DISCOD_ID_SECRET }}

    outputs:
      DISCORD_PRESENCE_DICT_MAP: ${{ steps.DISCORD_MAP_OUTPUT }}


    steps:
      - name: Step 1 | Repository Checkout
      - uses: actions/checkout@master

      - name: Step 2 | Dependency Installation (via PipEnv)
      - uses: |
          python -m pip install pipenv
          pipenv install

      - name: Step 3 | Database Checks (Read-Only)
      - run: |
          Do Some Linux Commands To Verify Integrity.
          pipenv shell
          python

      - name: Step 4 | Checking User's Discord Activity
      - run: |
          Do IF and ELSE if there's new or not. Like Time and Activity.
          If Not Available then Use Database To Trace Last Record.

      - name: Step 5 | Updating README's Discord Badge
      - run: |
